from pathlib import Path
from lxml import html, etree
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'dist'
source=html.fromstring((ROOT/'references/stitch/code.html').read_text(encoding='utf8'))
head=source.find('head')
for style in head.findall('style'): head.remove(style)
for script in head.findall('script'): head.remove(script)
for link in list(head.findall('link')):
    if 'Material+Symbols' in link.get('href',''): head.remove(link)
etree.SubElement(head,'title').text='Regan Yates | Technology Leadership & Architecture'
etree.SubElement(head,'meta',name='description',content='Regan Yates connects technical leadership, enterprise IT, systems architecture, and automation with business needs.')
etree.SubElement(head,'link',rel='stylesheet',href='/stitch.css')
etree.SubElement(head,'link',rel='stylesheet',href='/refinements.css')
etree.SubElement(head,'link',rel='icon',href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' fill='%231b1c1a'/%3E%3Ctext x='5' y='22' fill='%23faf9f5' font-family='serif' font-size='18'%3ERY%3C/text%3E%3C/svg%3E")
HEAD=html.tostring(head,encoding='unicode')
EMAIL='mailto:reganjeanyates@gmail.com'
LINKEDIN='https://www.linkedin.com/in/regan-yates-85ab711ba/'
GITHUB='https://github.com/rjyates'
HEADER='''<a class="skip" href="#main">Skip to content</a><header class="site-header"><nav class="site-nav" aria-label="Main navigation"><a class="brand" href="/" aria-label="Regan Yates home"><span class="monogram" aria-hidden="true">RY</span><span><strong>REGAN YATES</strong><small>TECH LEADERSHIP &amp; ARCHITECTURE</small></span></a><button class="menu-button" aria-expanded="false" aria-controls="main-nav" type="button">Menu</button><div class="nav-links" id="main-nav"><a href="/#leadership">Philosophy &amp;<br>Leadership</a><a href="/#work">Architecture &amp;<br>Selected Work</a><a href="/#projects">AI &amp;<br>Automation</a><a href="/#experience">Experience</a><a href="/#contact">Contact</a><a href="/links/">Quick Links</a></div><a class="action" href="/resume/">Background<br>&amp; Résumé</a></nav></header>'''
FOOTER=f'''<footer class="site-footer"><div class="container"><div class="footer-grid"><div><h3>Technical depth.<br>Leadership in practice.</h3><p>Connecting systems, people, and business needs through architecture, automation, and technical ownership.</p></div><div><div class="label">Location &amp; Contact</div><p>Fayetteville, Arkansas</p><a href="{EMAIL}">reganjeanyates@gmail.com</a></div><div><div class="label">Professional Channels</div><div class="footer-links"><a href="{LINKEDIN}">LinkedIn</a><a href="{GITHUB}">GitHub</a><a href="/links/">Quick links / digital business card</a><a href="/resume/">Background &amp; résumé</a></div></div></div><div class="footer-bottom"><span>© 2026 REGAN YATES</span><span>TECHNOLOGY · PEOPLE · PROCESS</span></div></div></footer>'''
def page(content,title=None):
    h=HEAD if title is None else HEAD.replace('Regan Yates | Technology Leadership &amp; Architecture',title)
    return '<!doctype html><html lang="en">'+h+'<body class="bg-surface font-body-md text-on-surface antialiased">'+HEADER+'<main id="main">'+content+'</main>'+FOOTER+'<script src="/site.js" defer></script></body></html>'
def section(content,extra='',tone='bg-surface'):
    return f'<section class="w-full px-margin md:px-margin-tablet lg:px-margin-desktop py-space-xl {tone}" {extra}><div class="max-w-7xl mx-auto">{content}</div></section>'
def brief(label,text,tone='bg-surface-container-low'):
    return f'<div class="p-space-md {tone} flex flex-col gap-space-sm"><h3 class="label">{label}</h3><p class="body-copy">{text}</p></div>'
HERO=section('''<div class="hero-layout"><div><p class="technical bronze">TECHNOLOGY LEADERSHIP // ARCHITECTURE &amp; AUTOMATION</p><h1 class="font-display-lg text-display-lg text-primary tracking-tight mt-3">Technical Decisions.<br>People. Business Impact.</h1><p class="hero-subtitle">Building systems with the bigger picture in mind.</p></div><aside class="p-space-md bg-surface-container-low"><span class="label">A practical perspective</span><p class="body-copy mt-2">I’m Regan Yates. I bring hands-on development and enterprise IT experience to improving systems, guiding technology decisions, and leading people.</p></aside></div><div class="taxonomy" id="work"><span class="label">Explore the work</span><div id="taxonomy-filters" role="group" aria-label="Filter selected work"><button type="button" data-filter="all" aria-pressed="true">All Work [03]</button><button type="button" data-filter="architecture" aria-pressed="false">Architecture</button><button type="button" data-filter="automation" aria-pressed="false">AI &amp; Automation</button></div><span class="technical filter-count" role="status" aria-live="polite">3 projects shown</span></div>''')
ONE=section('''<div class="case-strip"><div><span class="case-badge">PROJECT 01 / ONEGAUGE</span><span>AUTOMOTIVE TECHNOLOGY</span></div><span>APR 2026 – PRESENT // IN DEVELOPMENT</span></div><div class="grid grid-cols-1 lg:grid-cols-12 gap-gutter-desktop"><div class="lg:col-span-5 flex flex-col gap-space-lg"><div><h2 class="font-headline-xl text-headline-xl text-primary leading-tight">From Custom Firmware to a Configurable Platform</h2><p class="font-body-lg text-body-lg text-secondary mt-3">Helping shape the software direction for digital motorsports gauge systems.</p></div>'''+brief('The product challenge','Specialized vehicles and configurations require tailored firmware. The next step is a more scalable platform that gives customers greater control over configuration and vehicle-data visualization.','bg-surface-container')+brief('My role in the direction','As Technical Lead &amp; Developer, I lead software technology decisions, including tooling, architecture, and project-management systems. I develop embedded firmware and a customer-facing application intended to support self-service configuration.')+'''<div class="chips"><span>Embedded firmware</span><span>Software architecture</span><span>Product direction</span></div></div><div class="lg:col-span-7 flex flex-col gap-space-md"><div class="blueprint-board"><div class="board-heading"><span>FIG 1.1 / PRODUCT DIRECTION</span><span>CONCEPTUAL PROGRESSION</span></div><div class="blueprint"><div class="nodes"><div class="node"><span class="node-index">01</span><strong>Vehicle needs</strong><span>Specialized configurations</span></div><div class="node"><span class="node-index">02</span><strong>Gauge firmware</strong><span>Custom embedded behavior</span></div><div class="node"><span class="node-index">03</span><strong>Customer application</strong><span>Self-service configuration</span></div></div><div class="flowline" aria-hidden="true"><span>REQUIREMENTS</span><i></i><span>FIRMWARE</span><i></i><span>PLATFORM</span></div><div class="system-notes">[DIRECTION] Move toward a user-configurable platform.<br>[OWNERSHIP] Connect architecture and hands-on development.<br>[STATUS] Application and platform work are ongoing.</div></div><p class="board-caption">A summary of the product direction, not a deployed system architecture.</p></div><div class="metric-panel"><p class="label">Areas of ownership</p><div class="metric-grid"><div><strong>Direction</strong><span>Tooling &amp; architecture decisions</span></div><div><strong>Delivery</strong><span>Embedded firmware development</span></div><div><strong>Platform</strong><span>Customer application development</span></div></div></div></div></div>''','data-category="architecture" data-project="OneGauge"','bg-surface-container-lowest')
PROJECTS=section('''<p class="label bronze">Applied AI &amp; Systems Thinking</p><h2 class="section-title">Projects Built Around Real Workflows</h2><p class="body-copy max-w-3xl">Personal projects exploring how software can help people navigate information and automate everyday work.</p><div class="project-cards"><article class="project-card" data-category="automation" data-project="Luther"><span class="technical bronze">PROJECT 02 // RESEARCH TOOL BUILT</span><h3>Luther / Medieval History Research</h3><p>Built around a doctoral researcher’s workflow, Luther aggregates medieval-history journal content, summarizes articles and issues, and surfaces potential gaps and underexplored research questions.</p><div class="card-note">FOCUS: Bring content discovery and research exploration into a workflow shaped around its user.</div><div class="card-bottom">PERSONAL PROJECT · RESEARCH &amp; APPLIED AI</div></article><article class="project-card" data-category="architecture automation" data-project="Vera"><span class="technical bronze">PROJECT 03 // IN DESIGN &amp; DEVELOPMENT</span><h3>Vera / Local-First Automation</h3><p>I’m designing a self-hosted personal automation platform centered on local infrastructure, service integrations, and workflows, with explicit human approval for consequential external actions.</p><div class="card-note">FOCUS: Connect services while making system ownership and human oversight part of the design.</div><div class="card-bottom">PERSONAL PROJECT · SYSTEMS &amp; AUTOMATION</div></article></div>''','id="projects"','bg-surface-container-low')
ROLES='''<article class="role"><span class="technical bronze">APR 2026 – PRESENT</span><h3>Technical Lead &amp; Developer</h3><p class="organization">OneGauge Digital Gauges</p><p>Lead software technology decisions, develop custom embedded firmware, and help define a more scalable, user-configurable product platform.</p></article><article class="role"><span class="technical bronze">AUG 2024 – PRESENT</span><h3>Computer Support Analyst</h3><p class="organization">University of Arkansas System Division of Agriculture</p><p>Coordinate frontline IT operations, supervise two hourly staff, oversee endpoint preparation, and administer enterprise devices and accounts.</p></article><article class="role"><span class="technical bronze">SEP 2022 – JUL 2024</span><h3>Computer Lab Technician</h3><p class="organization">University of Arkansas · Electrical Engineering &amp; Computer Science</p><p>Supported research and instructional computing labs through OS deployment, software configuration, hardware setup, account administration, and troubleshooting across Windows, macOS, and Linux.</p></article><article class="role"><span class="technical bronze">MAR 2022 – AUG 2022</span><h3>Computer Science Research Assistant</h3><p class="organization">University of Arkansas</p><p>Contributed to the development and maintenance of web platforms supporting academic programs and research initiatives.</p></article>'''
EDUCATION='''<h3>Education</h3><p><strong>Master of Information Systems<br>Cybersecurity Management</strong><small>University of Arkansas · Sam M. Walton College of Business<br>Expected 2027</small></p><p><strong>BA in Computer Science</strong><small>University of Arkansas · 2024<br>Minor in Sociology/Criminology</small></p><p><strong>AS in Liberal Arts and Sciences</strong><small>Arkansas State University-Beebe · 2020</small></p>'''
SKILLS='''<h3>Technical Foundation</h3><p><strong>Cloud &amp; enterprise:</strong> Microsoft Azure, Intune, Active Directory, endpoint management, identity and access administration.</p><p><strong>Development &amp; scripting:</strong> C/C++, Java, Python, SQL, JavaScript, HTML/CSS, R, Bash, and PowerShell.</p><p><strong>Systems:</strong> Linux, Windows, macOS, Docker, embedded systems, and CAN bus.</p>'''
ABOUT=section('''<div class="about-grid"><div id="leadership"><p class="label bronze">Philosophy &amp; Leadership</p><h2 class="section-title">Ownership Beyond the Implementation</h2><p class="body-copy">I’m based in Fayetteville, Arkansas, with a background in computer science and experience across enterprise IT and software development. I’m most interested in the intersection of technical architecture, automation, leadership, and business strategy.</p><p class="body-copy">My next chapter is about broader ownership: guiding technology decisions, improving processes, and leading projects and people. I’m pursuing opportunities in technology management, systems architecture, platform engineering, and business transformation.</p><div class="philosophy">Understand the people and the process. Then build the system that serves them.</div></div><div id="experience"><p class="label mb-5">Professional Experience</p>'''+ROLES+'''</div></div><div class="credentials"><div>'''+EDUCATION+'''</div><div>'''+SKILLS+'''<h3 class="mt-6">Community</h3><p>Women in Technology of Northwest Arkansas; founding member of Girls in Tech at the University of Arkansas; University of Arkansas High School Programming Contest volunteer.</p></div></div>''')
CONTACT=section(f'''<div class="contact-panel"><div><p class="label bronze">Let’s Connect</p><h2>Technology That Moves an Organization Forward.</h2><p>I’m interested in opportunities to guide technology decisions, improve systems, and lead meaningful change. Let’s talk about what your team is building.</p></div><div class="contact-actions"><a class="action" href="{EMAIL}">Email Regan</a><a class="action outline" href="/resume/">View Background</a></div></div>''','id="contact"')
REMAINING=PROJECTS+ABOUT+CONTACT
OUT.joinpath('index.html').write_text(page(HERO+ONE+REMAINING),encoding='utf8')
(OUT/'links').mkdir(exist_ok=True)
links=f'''<main class="link-shell" id="main"><div class="monogram" aria-hidden="true">RY</div><p class="technical bronze">TECHNOLOGY · PEOPLE · PROCESS</p><h1>Regan Yates</h1><p class="link-intro">Technology leadership.<br>Systems architecture. Automation.</p><p class="bio">Hands-on technical experience with a focus on people, processes, and business needs.<br>Fayetteville, Arkansas.</p><nav aria-label="Professional links"><a class="link-item featured" href="/"><span><strong>Explore My Portfolio</strong><small>Selected work, experience, and approach</small></span><span aria-hidden="true">↗</span></a><a class="link-item" href="{EMAIL}"><span><strong>Let’s Talk</strong><small>Email me about opportunities or projects</small></span><span aria-hidden="true">↗</span></a><a class="link-item" href="{LINKEDIN}"><span><strong>Connect on LinkedIn</strong><small>Professional background and connections</small></span><span aria-hidden="true">↗</span></a><a class="link-item" href="{GITHUB}"><span><strong>Find Me on GitHub</strong><small>Code and development work</small></span><span aria-hidden="true">↗</span></a><a class="link-item" href="/resume/"><span><strong>Background &amp; Résumé</strong><small>Experience, education, and technical skills</small></span><span aria-hidden="true">↗</span></a></nav><p class="link-footer">REGAN YATES // FAYETTEVILLE, ARKANSAS</p></main>'''
(OUT/'links/index.html').write_text('<!doctype html><html lang="en">'+HEAD.replace('Regan Yates | Technology Leadership &amp; Architecture','Connect with Regan Yates')+'<body>'+links+'</body></html>',encoding='utf8')
(OUT/'resume').mkdir(exist_ok=True)
resume=section('''<p class="technical bronze">BACKGROUND &amp; RÉSUMÉ</p><h1 class="font-display-lg text-display-lg mt-3">Regan Yates</h1><p class="hero-subtitle">Technical leadership, systems architecture, and automation.</p><p class="body-copy mt-5 max-w-3xl">Technical lead and IT operations professional with experience spanning software and firmware development, enterprise endpoint administration, process automation, and team leadership.</p><div class="flex flex-wrap gap-3 mt-6"><a class="action" href="'''+EMAIL+'''">Get in Touch</a><a class="action outline" href="/#work">View Selected Work</a></div>''')+section('<div class="about-grid"><div><h2 class="section-title">Experience</h2>'+ROLES+'</div><div class="credentials" style="display:block;margin-top:0">'+EDUCATION+'<div class="mt-8">'+SKILLS+'</div><h3 class="mt-8">Professional Involvement</h3><p>Women in Technology of Northwest Arkansas; founding member of Girls in Tech at the University of Arkansas; University of Arkansas High School Programming Contest volunteer.</p></div></div>')
(OUT/'resume/index.html').write_text(page(resume,'Regan Yates | Background &amp; Résumé'),encoding='utf8')
