from pathlib import Path
from lxml import html, etree
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'dist'
source=html.fromstring((ROOT/'references/stitch/code.html').read_text(encoding='utf8'))
head=source.find('head')
for style in head.findall('style'): head.remove(style)
for script in head.findall('script'): head.remove(script)
for link in list(head.findall('link')):
    if 'Material+Symbols' in link.get('href',''): head.remove(link)
etree.SubElement(head,'title').text='Regan Yates | Technology Leadership & Architecture'
etree.SubElement(head,'meta',name='description',content='Regan Yates connects technical leadership, enterprise IT, systems architecture, and automation with business needs.')
etree.SubElement(head,'link',rel='stylesheet',href='/stitch.css')
etree.SubElement(head,'link',rel='stylesheet',href='/refinements.css?v=overview-1')
etree.SubElement(head,'link',rel='icon',href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' fill='%231b1c1a'/%3E%3Ctext x='5' y='22' fill='%23faf9f5' font-family='serif' font-size='18'%3ERY%3C/text%3E%3C/svg%3E")
HEAD=html.tostring(head,encoding='unicode')
EMAIL='mailto:reganjeanyates@gmail.com'
LINKEDIN='https://www.linkedin.com/in/regan-yates-85ab711ba/'
GITHUB='https://github.com/rjyates'
HEADER='''<a class="skip" href="#main">Skip to content</a><header class="site-header"><nav class="site-nav" aria-label="Main navigation"><a class="brand" href="/" aria-label="Regan Yates home"><span class="monogram" aria-hidden="true">RY</span><span><strong>REGAN YATES</strong><small>TECH LEADERSHIP &amp; ARCHITECTURE</small></span></a><button class="menu-button" aria-expanded="false" aria-controls="main-nav" type="button">Menu</button><div class="nav-links" id="main-nav"><a href="/#focus">What I Do</a><a href="/#work">Projects</a><a href="/#approach">My Approach</a><a href="/#direction">My Direction</a><a href="/#contact">Contact</a><a href="/links/">Quick Links</a></div><a class="action" href="/resume/">Background<br>&amp; Résumé</a></nav></header>'''
FOOTER=f'''<footer class="site-footer"><div class="container"><div class="footer-grid"><div><h3>Technical depth.<br>Leadership in practice.</h3><p>Connecting systems, people, and business needs through architecture, automation, and technical ownership.</p></div><div><div class="label">Location &amp; Contact</div><p>Fayetteville, Arkansas</p><a href="{EMAIL}">reganjeanyates@gmail.com</a></div><div><div class="label">Professional Channels</div><div class="footer-links"><a href="{LINKEDIN}">LinkedIn</a><a href="{GITHUB}">GitHub</a><a href="/links/">Quick links / digital business card</a><a href="/resume/">Background &amp; résumé</a></div></div></div><div class="footer-bottom"><span>© 2026 REGAN YATES</span><span>TECHNOLOGY · PEOPLE · PROCESS</span></div></div></footer>'''
def page(content,title=None):
    h=HEAD if title is None else HEAD.replace('Regan Yates | Technology Leadership &amp; Architecture',title)
    return '<!doctype html><html lang="en">'+h+'<body class="bg-surface font-body-md text-on-surface antialiased">'+HEADER+'<main id="main">'+content+'</main>'+FOOTER+'<script src="/site.js?v=overview-1" defer></script></body></html>'
def section(content,extra='',tone='bg-surface'):
    return f'<section class="w-full px-margin md:px-margin-tablet lg:px-margin-desktop py-space-xl {tone}" {extra}><div class="max-w-7xl mx-auto">{content}</div></section>'
def brief(label,text,tone='bg-surface-container-low'):
    return f'<div class="p-space-md {tone} flex flex-col gap-space-sm"><h3 class="label">{label}</h3><p class="body-copy">{text}</p></div>'
HERO=section('''<div class="overview-hero"><p class="technical bronze">REGAN YATES / TECHNOLOGY &amp; LEADERSHIP</p><h1>Building technology.<br>Connecting the bigger picture.</h1><p class="overview-intro">I work across software, systems, and automation—with an interest in how technology decisions shape the way people and organizations work.</p><p class="overview-intro secondary-intro">My direction is technology leadership: bringing hands-on understanding to architecture, team leadership, and business strategy.</p><a class="text-link" href="#direction">Where I’m headed <span aria-hidden="true">↘</span></a></div>''')
FOCUS=section('''<div class="overview-section-heading"><div><p class="label bronze">What I Do</p><h2 class="section-title">From the system<br>to the way it’s used.</h2></div><p class="body-copy">My experience spans enterprise IT and software development. What interests me most is connecting the technical work to a useful purpose.</p></div><div class="focus-grid"><article><span class="technical bronze">01 / SYSTEMS</span><h3>Build &amp; connect</h3><p>Develop software and think through how the pieces fit together—from embedded firmware to applications and the infrastructure behind them.</p></article><article><span class="technical bronze">02 / AUTOMATION</span><h3>Improve how work happens</h3><p>Explore ways to reduce repetitive effort, connect services, and make information more useful through automation and applied AI.</p></article><article><span class="technical bronze">03 / LEADERSHIP</span><h3>Guide the next step</h3><p>Bring technical context to decisions, coordinate people and projects, and connect day-to-day work with a longer-term direction.</p></article></div>''','id="focus"','bg-surface-container-lowest')
PROJECTS=section('''<div class="overview-section-heading"><div><p class="label bronze">Selected Projects</p><h2 class="section-title">A few ways that takes shape.</h2></div><p class="body-copy">Product development, research, and personal automation—different contexts for the same interest in building useful systems.</p></div><div class="project-overviews"><article data-project="OneGauge"><div><span class="technical bronze">01 / PRODUCT DEVELOPMENT</span><h3>OneGauge</h3></div><p>Developing firmware and helping shape a more configurable digital gauge platform for motorsports. A place where hands-on engineering meets product direction.</p><span class="project-stage">Ongoing professional work</span></article><article data-project="Luther"><div><span class="technical bronze">02 / RESEARCH &amp; AI</span><h3>Luther</h3></div><p>A research tool built around a doctoral researcher’s workflow, bringing medieval-history journal content, summaries, and potential research questions together.</p><span class="project-stage">Personal project · Built</span></article><article data-project="Vera"><div><span class="technical bronze">03 / SYSTEMS &amp; AUTOMATION</span><h3>Vera</h3></div><p>A local-first personal automation platform I’m designing to connect services and workflows, with human oversight built into consequential actions.</p><span class="project-stage">Personal project · In development</span></article></div>''','id="work"')
APPROACH=section('''<div class="overview-section-heading"><div><p class="label bronze">My Approach</p><h2 class="section-title">Start with the work.<br>Understand the people.</h2></div><div><p class="body-copy">I’m drawn to the questions around the implementation: What problem are we solving? Who needs to use this? How will it fit into the way the organization works?</p><p class="body-copy mt-5">That perspective connects my interests in architecture, automation, and leadership. I want to make technology decisions with enough technical depth to understand the tradeoffs—and enough context to know why they matter.</p></div></div>''','id="approach"','bg-surface-container-low')
DIRECTION=section('''<div class="direction-layout"><div><p class="label bronze">Where I’m Headed</p><h2 class="section-title">Broader ownership.<br>Thoughtful technology leadership.</h2></div><div><p class="body-copy">I’m building toward IT Director and Director of Technology roles, with CTO as a long-term goal. The work I’m pursuing now brings together technical decisions, systems ownership, process improvement, and leading people.</p><p class="body-copy mt-5">I’m especially interested in technology management, solutions and systems architecture, automation and platform engineering, and business transformation.</p><p class="direction-footnote">Based in Fayetteville, Arkansas. Currently pursuing a master’s in Information Systems with a focus in Cybersecurity Management.</p><a class="text-link" href="/resume/">Explore my background <span aria-hidden="true">↗</span></a></div></div>''','id="direction"')
ROLES='''<article class="role"><span class="technical bronze">APR 2026 – PRESENT</span><h3>Technical Lead &amp; Developer</h3><p class="organization">OneGauge Digital Gauges</p><p>Lead software technology decisions, develop custom embedded firmware, and help define a more scalable, user-configurable product platform.</p></article><article class="role"><span class="technical bronze">AUG 2024 – PRESENT</span><h3>Computer Support Analyst</h3><p class="organization">University of Arkansas System Division of Agriculture</p><p>Coordinate frontline IT operations, supervise two hourly staff, oversee endpoint preparation, and administer enterprise devices and accounts.</p></article><article class="role"><span class="technical bronze">SEP 2022 – JUL 2024</span><h3>Computer Lab Technician</h3><p class="organization">University of Arkansas · Electrical Engineering &amp; Computer Science</p><p>Supported research and instructional computing labs through OS deployment, software configuration, hardware setup, account administration, and troubleshooting across Windows, macOS, and Linux.</p></article><article class="role"><span class="technical bronze">MAR 2022 – AUG 2022</span><h3>Computer Science Research Assistant</h3><p class="organization">University of Arkansas</p><p>Contributed to the development and maintenance of web platforms supporting academic programs and research initiatives.</p></article>'''
EDUCATION='''<h3>Education</h3><p><strong>Master of Information Systems<br>Cybersecurity Management</strong><small>University of Arkansas · Sam M. Walton College of Business<br>Expected 2027</small></p><p><strong>BA in Computer Science</strong><small>University of Arkansas · 2024<br>Minor in Sociology/Criminology</small></p><p><strong>AS in Liberal Arts and Sciences</strong><small>Arkansas State University-Beebe · 2020</small></p>'''
SKILLS='''<h3>Technical Foundation</h3><p><strong>Cloud &amp; enterprise:</strong> Microsoft Azure, Intune, Active Directory, endpoint management, identity and access administration.</p><p><strong>Development &amp; scripting:</strong> C/C++, Java, Python, SQL, JavaScript, HTML/CSS, R, Bash, and PowerShell.</p><p><strong>Systems:</strong> Linux, Windows, macOS, Docker, embedded systems, and CAN bus.</p>'''
CONTACT=section(f'''<div class="contact-panel"><div><p class="label bronze">Let’s Connect</p><h2>Technology That Moves an Organization Forward.</h2><p>I’m interested in opportunities to guide technology decisions, improve systems, and lead meaningful change. Let’s talk about what your team is building.</p></div><div class="contact-actions"><a class="action" href="{EMAIL}">Email Regan</a><a class="action outline" href="/resume/">View Background</a></div></div>''','id="contact"')
REMAINING=FOCUS+PROJECTS+APPROACH+DIRECTION+CONTACT
OUT.joinpath('index.html').write_text(page(HERO+REMAINING),encoding='utf8')
(OUT/'links').mkdir(exist_ok=True)
links=f'''<main class="link-shell" id="main"><div class="monogram" aria-hidden="true">RY</div><p class="technical bronze">TECHNOLOGY · PEOPLE · PROCESS</p><h1>Regan Yates</h1><p class="link-intro">Technology leadership.<br>Systems architecture. Automation.</p><p class="bio">Hands-on technical experience with a focus on people, processes, and business needs.<br>Fayetteville, Arkansas.</p><nav aria-label="Professional links"><a class="link-item featured" href="/"><span><strong>Explore My Portfolio</strong><small>Selected work, experience, and approach</small></span><span aria-hidden="true">↗</span></a><a class="link-item" href="{EMAIL}"><span><strong>Let’s Talk</strong><small>Email me about opportunities or projects</small></span><span aria-hidden="true">↗</span></a><a class="link-item" href="{LINKEDIN}"><span><strong>Connect on LinkedIn</strong><small>Professional background and connections</small></span><span aria-hidden="true">↗</span></a><a class="link-item" href="{GITHUB}"><span><strong>Find Me on GitHub</strong><small>Code and development work</small></span><span aria-hidden="true">↗</span></a><a class="link-item" href="/Regan_Yates_Resume.pdf" download="Regan_Yates_Resume.pdf"><span><strong>Download My Résumé</strong><small>PDF · Experience, education, and skills</small></span><span aria-hidden="true">↗</span></a></nav><p class="link-footer">REGAN YATES // FAYETTEVILLE, ARKANSAS</p></main>'''
(OUT/'links/index.html').write_text('<!doctype html><html lang="en">'+HEAD.replace('Regan Yates | Technology Leadership &amp; Architecture','Connect with Regan Yates')+'<body>'+links+'</body></html>',encoding='utf8')
(OUT/'resume').mkdir(exist_ok=True)
resume=section('''<p class="technical bronze">BACKGROUND &amp; RÉSUMÉ</p><h1 class="font-display-lg text-display-lg mt-3">Regan Yates</h1><p class="hero-subtitle">Technical leadership, systems architecture, and automation.</p><p class="body-copy mt-5 max-w-3xl">Technical lead and IT operations professional with experience spanning software and firmware development, enterprise endpoint administration, process automation, and team leadership.</p><div class="flex flex-wrap gap-3 mt-6"><a class="action" href="/Regan_Yates_Resume.pdf" download="Regan_Yates_Resume.pdf">Download Résumé (PDF)</a><a class="action" href="'''+EMAIL+'''">Get in Touch</a><a class="action outline" href="/#work">View Selected Work</a></div>''')+section('<div class="about-grid"><div><h2 class="section-title">Experience</h2>'+ROLES+'</div><div class="credentials" style="display:block;margin-top:0">'+EDUCATION+'<div class="mt-8">'+SKILLS+'</div><h3 class="mt-8">Professional Involvement</h3><p>Women in Technology of Northwest Arkansas; founding member of Girls in Tech at the University of Arkansas; University of Arkansas High School Programming Contest volunteer.</p></div></div>')
(OUT/'resume/index.html').write_text(page(resume,'Regan Yates | Background &amp; Résumé'),encoding='utf8')
